### ISSUE TITLE
Creación de registro de usuario con base de datos ndb

### ISSUE THREAD

**Issue by juanfranrv** [julioxus/iv-aerospace#49]

**Comment by juanfranrv** [comment]
Informándome sobre la base de datos 'nbd' de Python para realizar el registro de usuarios y el posterior login del usuario a la web

**Comment by Ariacus** [comment]
Hacer que cuando un usuario se registre, directamente entre como logeado y no tenga que iniciar sesión

**Comment by Ariacus** [comment]
Hacer que cuando se le da al botón "Registrarse" se limpien los campos Usuario y Contraseña.
