### ISSUE TITLE
Base de datos sólo disponible en despliegue

### ISSUE THREAD

**Issue by julioxus** [julioxus/iv-aerospace#60]
@JJ Para nuestra aplicación estamos usando la Datastore de Google mediante [NDB](https://cloud.google.com/appengine/docs/python/ndb/ ), el problema es que sólo podemos usar la base de datos si la aplicación está desplegada en App Engine, así que no podemos usarla en local, cosa que dará problemas si la queremos desplegar en un IaaS. ¿Deberíamos usar Mongo u otra similar?

**Comment by JJ** [comment]
Si es a nivel de test, casi todos los lenguajes tienen librerías (llamadas
"mock") que te permiten testear bases de datos sin tener acceso a las
mismas.
Si decidís usar Mongo (hay DBaaS que podéis usar desde cualquier otro lado)
que sea una decisión técnica, no por los requisitos para presentar el
proyecto en la asignatura.

**Comment by julioxus** [comment]
El problema era que no guardábamos la base de datos localmente. Se puede hacer con el parámetro --storage-path=... como se indica [aquí](https://cloud.google.com/appengine/docs/python/tools/devserver#Python_Command-line_arguments) para indicar donde se guarda la base de datos local tipo SQLite

**Comment by julioxus** [comment]
El problema era que no guardábamos la base de datos localmente. Se puede hacer con el parámetro --storage-path=... como se indica [aquí](https://cloud.google.com/appengine/docs/python/tools/devserver#Python_Command-line_arguments) para indicar donde se guarda la base de datos local tipo SQLite
