### ISSUE TITLE
Problemas con provisionamiento

### ISSUE THREAD

**Issue by julioxus** [julioxus/iv-aerospace#71]
@JJ ayer estuvimos investigando IaaS para realizar la parte de provisionamiento del proyecto pero en todos los IaaS (Amazon, Azure, HP, Koding...) nos piden introducir tarjeta de crédito. ¿Hay algún otro servicio que podamos usar sin tener que hacer esto?

**Comment by JJ** [comment]
¿No tenéis el cupón de Azure activado? En cuanto a Koding, si tienes la
máquina conectada se puede usar sin tarjeta de crédito.. Finalmente, probad
Fi-Ware a ver si va.

El 25 de enero de 2015, 12:07, Julio Martínez Martínez-Checa <
notifications@github.com> escribió:

> @JJ <https://github.com/JJ> ayer estuvimos investigando IaaS para
> realizar la parte de provisionamiento del proyecto pero en todos los IaaS
> (Amazon, Azure, HP, Koding...) nos piden introducir tarjeta de crédito.
> ¿Hay algún otro servicio que podamos usar sin tener que hacer esto?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/julioxus/iv-aerospace/issues/71>.
>



-- 
JJ

**Comment by julioxus** [comment]
No tenemos el cupón de Azure, si tiene alguna cuenta de Azure que podamos usar se lo agradecería. De todas formas probaremos con Koding o Fi-Ware. Gracias

**Comment by JJ** [comment]
El problema es que los cupones no usados han caducado. He solicitado que me
los reactiven, pero no sé si lo harán.

El 25 de enero de 2015, 12:16, Julio Martínez Martínez-Checa <
notifications@github.com> escribió:

> No tenemos el cupón de Azure, si tiene alguna cuenta de Azure que podamos
> usar se lo agradecería. De todas formas probaremos con Koding o Fi-Ware.
> Gracias
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/julioxus/iv-aerospace/issues/71#issuecomment-71367121>
> .
>



-- 
JJ

**Comment by Ariacus** [comment]
@JJ tengo una pregunta para usted... quizás es que aun no entiendo demasiado del tema, pero no termino de encontrarle el sentido de si ya tenemos la aplicación en un PaaS como GAE, para que necesitamos un IaaS?

**Comment by JJ** [comment]
Por si la aplicación se hace mayor y necesita una máquina virtual para ella
solita.

El 25 de enero de 2015, 18:38, Jose Antonio Plata <notifications@github.com>
escribió:

> @JJ <https://github.com/JJ> tengo una pregunta para usted... quizás es
> que aun no entiendo demasiado del tema, pero no termino de encontrarle el
> sentido de si ya tenemos la aplicación en un PaaS como GAE, para que
> necesitamos un IaaS?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/julioxus/iv-aerospace/issues/71#issuecomment-71382667>
> .
>



-- 
JJ
